### ISSUE TITLE
[Bug] Parallel hint not applied on Global temporary table using incremental mode

### ISSUE THREAD

**Issue by philiphagglund** [oracle/dbt-oracle#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding parallel hint on a dbt model with incremental materialization the global temporary table does not run in parallel.

```
version: 2

models:
  - name: test
    config:
      materialized: incremental
      table_compression_clause: 'row store compress advanced'
      unique_key: ['account_key', 'effective_ts']
      tags: [dv_bancs, satellite]
      parallel: 8
```

Global temporary table creation:
```
create global temporary table o$pt_test115350300224
on commit preserve rows
as
select 
   ...
 ```
 
 Merge part:
 ```
 merge  /*+parallel(8)*/  into test DBT_INTERNAL_DEST
          using o$pt_test115350300224 DBT_INTERNAL_SOURCE
 ```

### Expected Behavior

We would expect that the hint also reflects on the global temporary table. So creation of the GTT would be running in parallel also

In example
```
create global temporary table o$pt_test115350300224
parallel 8
on commit preserve rows
as
select 
   ...
 ```

### What Oracle database version are you using dbt with?

19c on-premis
