### ISSUE TITLE
[Feature] Insert with /*+ append */ hint

### ISSUE THREAD

**Issue by philiphagglund** [oracle/dbt-oracle#174]
### Describe the Feature

We want to be able to toogle between running insert statements with /*+ append */ hint and not. Be making it possible users can choose between running a `conventional dml` or using `direct path`. It would give us possibility to run direct path on serially dmls and not only running with parallel hint. 

It should be included in the:
```
  - name: hcc_table
    config:
      materialized: incremental
```
and in the incremental_strategy:
```
  - name: hcc_table
    config:
      materialized: incremental
      incremental_strategy: delete+insert
      unique_key: ['id', 'ts']
```

### Describe alternatives you've considered

Add a config parameter with maybe `insert_mode: append`

### Who will this benefit?

Everyone wanting to have bulk inserts above high water mark of tables.
